---
- name: Install .NET Framework 4.5.2
  hosts: win
  gather_facts: false
  tasks:
    - name: Ensure destination directory for .NET installer exists
      win_file:
        path: C:\temp
        state: directory

    - name: Download .NET Framework 4.5.2 installer
      win_get_url:
        url: https://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe
        dest: C:\temp

    - name: Install .NET Framework 4.5.2
      win_package:
        path: C:\temp\NDP452-KB2901907-x86-x64-AllOS-ENU.exe
        arguments: /quiet /norestart
        state: present

    - name: Remove .NET installer
      win_file:
        path: C:\temp\NDP452-KB2901907-x86-x64-AllOS-ENU.exe
        state: absent
