---
- name: Desinstalar WinRAR en equipos Windows
  hosts: win
  gather_facts: false
  tasks:
    - name: Desinstalar WinRAR
      win_shell: |
        $appName = "WinRAR"
        $uninstallString = (Get-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" | Where-Object { $_.DisplayName -eq $appName }).UninstallString
        if ($uninstallString) {
          Start-Process $uninstallString -Wait
        } else {
          Write-Host "WinRAR no está instalado en el sistema."
        }
