---
- name: Desinstalar aplicaci칩n de terceros en equipos Windows
  hosts: win
  gather_facts: false
  tasks:
    - name: Desinstalar aplicaci칩n
      win_shell: |
        $appName = "VideoLAN"
        $uninstallString = (Get-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" | Where-Object { $_.DisplayName -eq $appName }).UninstallString
        if ($uninstallString) {
          Start-Process $uninstallString -Wait
        } else {
          Write-Host "La aplicaci칩n $appName no est치 instalada."
        }
