---
- name: Obtener y cambiar nombre del equipo Windows
  hosts: win
  gather_facts: false
  tasks:
    - name: Obtener nombre actual del equipo
      win_shell: $env:COMPUTERNAME
      register: current_hostname

    - name: Mostrar nombre actual del equipo
      debug:
        var: current_hostname.stdout

    - name: Cambiar nombre del equipo
      win_shell: Rename-Computer -NewName "pc_ansible1" -Force
      args:
        executable: powershell.exe
      when: current_hostname.stdout != "pc_ansible1"  # Reemplaza "NuevoNombre" con el nuevo nombre deseado
