---
- name: Instalar VLC en equipos Windows
  hosts: win
  gather_facts: false
  
  tasks:
    - name: Crear carpeta en "C:\Temp"
      win_file:
      path: C:\Temp
      state: directory

    - name: Descargar el instalador de VLC en "C:\Temp"
      win_get_url:
        url: 'https://download.videolan.org/pub/videolan/vlc/last/win64/vlc-{{ vlc_version }}-win64.exe'
        dest: C:\Temp\vlc_installer.exe

    - name: Instalar VLC
      win_shell: |
        Start-Process -Wait -FilePath C:\Temp\vlc_installer.exe -ArgumentList '/S'

  vars:
    vlc_version: '3.0.20'  # Reemplaza con la versión de VLC que deseas instalar

    - name: Eliminar instalador descargado en "C:\Temp"
      win_file:
      path: C:\Temp\vlc-3.0.20-win32.exe
      state: absent
